-- AlterTable
ALTER TABLE "AppSettings" ALTER COLUMN "defaultLdTimes" SET DEFAULT ARRAY['00:00', '12:00', '16:00', '20:00']::TEXT[],
ALTER COLUMN "defaultJpTimes" SET DEFAULT ARRAY['00:15']::TEXT[],
ALTER COLUMN "bidPrizeJP" SET DEFAULT 3,
ALTER COLUMN "winningPrizeJP" SET DEFAULT 80000,
ALTER COLUMN "ldBidLimitPerNumber" SET DEFAULT 120;
